// lib/components/Project/Project.tsx
import React from 'react'
import { FaGithub, FaLink } from 'react-icons/fa'

type ProjectType = {
  name: string
  description: string
  previewUrl: string
  codeUrl: string
  image: string
}

const Project: React.FC<ProjectType> = ({
  name,
  description,
  previewUrl,
  codeUrl,
  image,
}) => {
  const urlFor = (source: string) => {
    const baseUrl = 'https://cdn.sanity.io/images/vmr0uhcd/production/'
    const image = source.split('image-')[1].replace('-webp', '.webp')
    return baseUrl + image
  }

  return (
    <div className="text-center pt-7 pb-16">
      <h1 className="underline font-semibold text-3xl">{name}</h1>
      <p className="py-2 text-lg">{description}</p>
      <img src={urlFor(image)} alt="Project Image" className="rounded-xl" />
      <div className="flex justify-center w-full pt-4">
        <a href={codeUrl} target="_blank" className="px-2">
          <FaGithub size={36}></FaGithub>
        </a>
        <a href={previewUrl} target="_blank" className="px-2">
          <FaLink size={36}></FaLink>
        </a>
      </div>
    </div>
  )
}

export default Project

// src/lib/components/Project.svelte
<script lang="ts">
	export let codeUrl: string;
	export let previewUrl: string;
	export let name: string;
	export let description: string;
	export let image: string;

	const urlFor = (source: string) => {
		const baseUrl = 'https://cdn.sanity.io/images/vmr0uhcd/production/';
		const image = source.split('image-')[1].replace('-webp', '.webp');
		return baseUrl + image;
	};
</script>

<div class="bg-[#0D0D0D] py-4 px-6 mt-4 mb-12 rounded-xl shadow-md flex flex-col h-42">
	<h1 class="font-bold text-xl md:text-3xl">{name}</h1>
	<p class="my-2 text-sm md:text-base">{description}</p>

	<img src={urlFor(image)} alt="Project" class="my-2" />
	<div class="font-bold text-right md:text-base flex self-end my-2 md:pt-0">
		<a href={codeUrl} class="underline mx-2">code</a>
		<a href={previewUrl} class="underline">preview</a>
	</div>
</div>
